<h1>Create a new account!</h1>
<div class="formContainer">
	<h2>Apply as a Designer</h2>
	<p>Please fill out the information below. * Designates required fields.</p>
	<p><em>Note: Proof of Tax ID is required. Please either fax a copy to [fax number] or upload a copy using form below.</em></p>
<?php 
	if( !empty($this->customSuccessMessages) ) {
		echo "<ul class='success customMessages'>";
		foreach( $this->customSuccessMessages as $successMessage ) echo "<li>" . $successMessage . "</li>";
		echo "</ul>";
	}

	if( !empty($this->customErrorMessages) ) {
		echo "<ul class='error customMessages'>";
		foreach( $this->customErrorMessages as $error ) echo "<li>" . $error . "</li>";
		echo "</ul>";
	}

	echo $this->registerDesignerForm;
?>
</div>
