<h2>Update your information</h2>
<div class="formContainer">
	<h2>Upload a new document.</h2>
	<p>Use the form below to upload a new tax id document.</p>
<?php 
	if( !empty($this->customSuccessMessages) ) {
		echo "<ul class='success customMessages'>";
		foreach( $this->customSuccessMessages as $successMessage ) echo "<li>" . $successMessage . "</li>";
		echo "</ul>";
	}

	if( !empty($this->customErrorMessages) ) {
		echo "<ul class='error customMessages'>";
		foreach( $this->customErrorMessages as $error ) echo "<li>" . $error . "</li>";
		echo "</ul>";
	}

	echo $this->updateDesignerDocumentForm;
?>
	<p><a href="/designer/update/">Done making changes.</a></p>
</div>
