<h2>Update your information</h2>
<div class="formContainer">
	<h2>Update your designer information.</h2>
	<p>Update your information as necessary. * Designates required fields.</p>
	<!-- <p><em>Note: Proof of Tax ID is required. Please either fax a copy to [fax number] or upload a copy using form below.</em></p> -->
<?php 
	if( !empty($this->customSuccessMessages) ) {
		echo "<ul class='success customMessages'>";
		foreach( $this->customSuccessMessages as $successMessage ) echo "<li>" . $successMessage . "</li>";
		echo "</ul>";
	}

	if( !empty($this->customErrorMessages) ) {
		echo "<ul class='error customMessages'>";
		foreach( $this->customErrorMessages as $error ) echo "<li>" . $error . "</li>";
		echo "</ul>";
	}

	echo $this->updateDesignerDetailsForm;
?>
	<p><a href="/designer/update/">Done making changes.</a></p>
</div>
