<html>
<body>
	<h1>A new submission has been made by a Designer.</h1>
	<ul>
		<li>Business: <?php echo $this->businessName ?></li>
		<li>Owner Name: <?php echo $this->businessOwnerName ?></li>
	</ul>
	<p>Please review the application and "Approve" or "Deny" the designer.</p>
	<p><a href="<?php echo $this->loginURL ?>">Login to your Admin Account to view the Designer applications.</a></p>
</body>
</html>