<html>
<body>
	<h1>You have submitted a new order.</h1>
	<ul>
		<li>Order date: <?php echo $this->todaysDate ?></li>
		<li>Submitted by: <?php echo $this->businessName . ", " . $this->businessOwnerName ?></li>
	</ul>
	<p>Items ordered:</p>
	<ul>
	<?php
		foreach($this->basketItemsDataArr as $basketItem)
		{
		?>
		<li>
			<dl>
				<dt>Quantity:</dt>
				<dd><?php echo $basketItem['quantity'] ?></dd>

				<dt>Stock Number:</dt>
				<dd><?php echo $basketItem['stock_number'] ?></dd>
			
				<dt>Description:</dt>
				<dd><?php echo $basketItem['description'] ?></dd>
			
				<?php
				if( $basketItem['notes'] ) {
				?>
				<dt>Notes:</dt>
				<dd><?php echo $basketItem['notes'] ?></dd>
				<?php
				}
				?>

				<dt>Unit Price:</dt>
				<dd><?php echo $basketItem['unit_price'] ?></dd>

				<dt>Total Price:</dt>
				<dd><?php echo $basketItem['total_item_price'] ?></dd>
			</dl>
		</li>
		<?php
		}
	?>
	</ul>
	<p>Grand Total: $<?php echo $this->grandTotal ?></p>

	<!-- <p><a href="<?php echo $this->loginURL ?>">Login to your Admin Account to view the Designer applications.</a></p> -->
</body>
</html>