<html>
<body>
	<p>Thanks for applying <?php echo $this->name ?>!</p>
	<p>Your application has been reviewed and your status has now been updated.</p>
	<p>Your current status is: "<?php echo $this->status ?>"</p>
	<p>Feel free to contact us if you have any questions.</p>
	<p>Thank you.</p>
	<p><a href="<?php echo $this->loginURL ?>">Login to your Designer Account to view your current status.</a></p>
</body>
</html>